### ISSUE TITLE
A way to remove assigned dates from task?

### ISSUE THREAD

**Issue by ruqqq** [cs2103jan2015-t09-1j/main#102]
@wksim91 @tlx2103 @ChenSijie 

We don't have this implemented at the moment right?

**Comment by wksim91** [comment]
I don't think this is a requirement. But yes, I do see the practicality in this. Sometimes user just wants to  remove the date.

**Comment by ruqqq** [comment]
I'm quite sure it is part of requirement as by definition it is part of CRUD. Since we are able to create tasks with different types (floating, deadline etc.), by definition should be able to edit too, right?

**Comment by wksim91** [comment]
Refer to git commit
