### ISSUE TITLE
As a user I can edit a recorded task

### ISSUE THREAD

**Issue by wksim91** [cs2103jan2015-t09-1j/main#11]
...so that I can correct any mistakes made previously

**Comment by ruqqq** [comment]
I recall current implementation have some minor issue. Moving to V0.2.

**Comment by wksim91** [comment]
Added support to edit priority attribute on data side.

**Comment by wksim91** [comment]
Issue solved. Closed for now. (May be opened when we implement other attributes: priority, recurring etc)
