### ISSUE TITLE
Bug: Add Do Assignments by EE2024 by Friday

### ISSUE THREAD

**Issue by wksim91** [cs2103jan2015-t09-1j/main#114]
Add Do Assignments by EE2024 by Friday

Results:  TASKNAME = Do Assignments by EE2024 by
              DUEDATE = Friday

**Comment by ruqqq** [comment]
Partially fixed by commit d9cdb5af2efc9776f8199eb14ef031b27fd2dd45 and a6ce3400da4bf25e263d91625e6de0116a567c03.

Working - add do assignment by ee2024 on Friday
Not Working - add do assignment by ee2024 from Friday to Saturday
Workaround - add "do assignment by ee2024" from Friday to Saturday
