### ISSUE TITLE
Bug? Show by Tomorrow doesn't move the list to tasks due tomorrow

### ISSUE THREAD

**Issue by wksim91** [cs2103jan2015-t09-1j/main#115]
"Show by Tomorrow" doesn't move the list to tasks due tomorrow

Instead it returns an exception

**Comment by ruqqq** [comment]
@wksim91 I can't replicate this. Can you paste the exception here?

**Comment by wksim91** [comment]
My bad, I can't replicate it too... Hasty judgement haha.
