### ISSUE TITLE
V0.5 User Manual (User Guide + Developer Guide) TODO

### ISSUE THREAD

**Issue by wksim91** [cs2103jan2015-t09-1j/main#119]
Guys, it is time. @ruqqq @ChenSijie @tlx2103 

This is mainly a todo list for what you guys gotta do. Helps to keep track of whats left.

User Guide requirements
1. Vet whatever I've done (I make mistakes!)
2. Check tonality

Before starting work, please read the Tutor's comment on V0.1. Can be found on IVLE uploads.

Developer Guide requirements
1. Update Architecture Diagram to new Architecture
2. Update/Generate Sequence Diagram (Make sure its the standard format)
3. Tutor mentioned that we "should" use seq diagram to explain Section 2
4. Generate JavaDocs for API instead (Tutor comment) (take the same component as V0.1)
5. Generate Class Diagrams and add in association links

By Friday Night:
1. User Guide finalised
2. Architecture Diagrams updated

Saturday Night
1. Sequence Diagrams (for all components? do we need so many? maybe not?)
2. All the "contextual" (aka written) stuff should be done

Sunday Afternoon
1. Check Developer guide over and over

I need help in obtaining the "generate-table" diagrams. Some stuff have been assigned (like diagrams) to Alex. And I've taken on the other parts, I can try to write as much as I can (i.e Known Issues section onwards). I believe you guys can help Alex on generating diagrams or something.

After looking through the tutor's comment, I don't think there is really _MUCH_ to work on. Since we already have a skeleton compared to the previous time, we don't have to start from scratch. Oh and yes, lets just ignore CS2101's comments. I can't really understand what they were driving at the last time...

I believe our coding side is _pretty much_ done. So this documentation is really the last bit.

GG Push mid end pls. k thx.

**Comment by ChenSijie** [comment]
For Javadocs we should edit in eclipse then som1 will generate javadocs for the whole project then use screen shots of HTML api to put in our V0.5?

ps my phone just died cant see whatsapp

**Comment by ruqqq** [comment]
For User Guide, what's missing:
1. Shortcut for scrolling is not in
2. Commands for scrolling not in (n, next, p, prev)
3. Command for "show due by <date>"
4. Tab to auto complete
5. Mini help window

**Comment by wksim91** [comment]
Thanks for the feedback. Sorry for missing them out haha. Working on it as of now!

**Comment by ruqqq** [comment]
Incomplete JavaDocs:
- Parser.java
- Storage.java
- Some of Command class not done

**Comment by ruqqq** [comment]
Dev Guide is missing:
- Command component
