### ISSUE TITLE
Implement update/edit task in Data class

### ISSUE THREAD

**Issue by ruqqq** [cs2103jan2015-t09-1j/main#36]

**Comment by ruqqq** [comment]
User story #11

**Comment by ruqqq** [comment]
Related to #21

**Comment by wksim91** [comment]
Changed "update" to "edit"

Completed basic function, awaiting completion of parser to continue.

**Comment by wksim91** [comment]
Added support to edit due date.

Sufficient for V0.1. Recommended to close.
