### ISSUE TITLE
Implement Recurring Tasks

### ISSUE THREAD

**Issue by wksim91** [cs2103jan2015-t09-1j/main#58]
Example
Add CS2103 every Monday

**Comment by wksim91** [comment]
Please discuss the implementation of this function.
1. Should multiple (infinite?) tasks be added once it is deemed as a recurring task?
2. or should only 1 task be added but displayed as "every Monday" on the date section in UI?

Personally I think 2 is more plausible. But its opened for discussions! :smile:

**Comment by ruqqq** [comment]
I vote for 2. Natty can parse repeating statements like "every Monday". Maybe we can get the day specified, and set the type of task to 'recurring'. (On a related noted, we haven't been using the type field which is kind of a bad thing. Haha.)

My UI will read the type of task, and accordingly display "every Monday".

**Comment by wksim91** [comment]
Yes, since Natty is powerful like that. I've added recurrence attributes to both task and commandInput classes. (Yes... I'll post an issue regarding refactoring of that)

Okay, that cleared things up about the implementation. Will update about the progress.

**Comment by ruqqq** [comment]
Not implementing.
