### ISSUE TITLE
Handle task title too long

### ISSUE THREAD

**Issue by ruqqq** [cs2103jan2015-t09-1j/main#79]
As mentioned by our tutor.

Discuss here how to handle it.

**Comment by ruqqq** [comment]
Task name now have more space to fit. This however does not work properly if the task name has no spaces.

On Command Edit side, need to implement check for task name an ensure no word is longer than a certain number of characters... perhaps 25 max char?

**Comment by wksim91** [comment]
Issue with taskname having no spaces is addressed.
