### ISSUE TITLE
Implement AutoComplete on Controller component

### ISSUE THREAD

**Issue by ruqqq** [cs2103jan2015-t09-1j/main#80]

**Comment by ruqqq** [comment]
Look in public String doAutoComplete(String userInput).

**Comment by ruqqq** [comment]
@tlx2103 Have you implemented auto complete for all commands? If not, shift this to V0.5.

**Comment by ruqqq** [comment]
Auto complete should be implemented for aliases too.

**Comment by tlx2103** [comment]
the autocomplete codes are there may need to fine tune move to v0.5

**Comment by tlx2103** [comment]
refined auto complete codes and pushed
