### ISSUE TITLE
Allow OmniTask to delete or add multiple tasks with single command?

### ISSUE THREAD

**Issue by tlx2103** [cs2103jan2015-t09-1j/main#94]
just my own opinion it might be more efficient to allow user to be able to add and delete multiple tasks in one command

**Comment by ruqqq** [comment]
I was thinking of this for the delete command. After much thought, I think it'll require a lot of architectural change to implement this because we will have to implement CommandInput and parser to detect multiple ids. The question is how? Ideas?

**Comment by wksim91** [comment]
^same. I was thinking of it just now and pfft, its not easy with our implementation. 

Idea was to create multiple calls of CommandDeleteImpl with the specified Ids in a single user input...

**Comment by tlx2103** [comment]
judging by the time we have left i guess just close this issue as we need to
 focus more on killing bugs
